In [21]:
import sqlite3
import pandas as pd


conn = sqlite3.connect(r"C:\\Users\\Asus\\Downloads\\Telegram Desktop\\task\\task\\chinook.db")

data=pd.read_sql_query("select * from invoices",conn)
customers = pd.read_sql_query("SELECT * FROM customers", conn)

invoice_items = pd.read_sql_query("SELECT * FROM invoice_items", conn)
tracks = pd.read_sql_query("SELECT * FROM tracks", conn)
albums = pd.read_sql_query("SELECT * FROM albums", conn)

In [ ]:
#exercise-1
data.groupby('CustomerId').agg({'Total':'sum'})
data.groupby('CustomerId').agg({'Total':'sum'}).sort_values(by='Total',ascending=False).head(5)

c=data.groupby(['CustomerId',]).agg({'Total':'sum'}).sort_values('Total',ascending=False).head(5)
customers.merge(c,how='inner',left_on='CustomerId',right_on='CustomerId')[['CustomerId','FirstName','LastName','Total']]

            Total
CustomerId
6           49.62
26          47.62
57          46.62
45          45.62
46          45.62

In [ ]:
invoice_items
albums
tracks
customers

In [37]:
#exercise-2
purchases=invoice_items.merge(tracks[['TrackId','AlbumId']],on='TrackId')

album_track_counts = purchases.groupby(['InvoiceId', 'AlbumId']).agg(
    TracksPurchased=('TrackId', 'count')
).reset_index()

album_total_tracks = tracks.groupby('AlbumId').agg(
    TotalTracks=('TrackId', 'count')
).reset_index()

comparison = album_track_counts.merge(album_total_tracks, on='AlbumId')

comparison['IsFullAlbum'] = comparison['TracksPurchased'] == comparison['TotalTracks']
comparison = comparison.merge(data[['InvoiceId', 'CustomerId']], on='InvoiceId')

customer_pref = comparison.groupby('CustomerId')['IsFullAlbum'].any().reset_index()

customer_pref['Preference'] = customer_pref['IsFullAlbum'].apply(
    lambda x: 'Full Albums' if x else 'Individual Tracks'
)

summary = customer_pref['Preference'].value_counts(normalize=True) * 100
summary_df = summary.reset_index()
summary_df.columns = ['Preference', 'Percentage']

In [ ]:
\

     AlbumId                                              Title  ArtistId
0          1              For Those About To Rock We Salute You         1
1          2                                  Balls to the Wall         2
2          3                                  Restless and Wild         2
3          4                                  Let There Be Rock         1
4          5                                           Big Ones         3
..       ...                                                ...       ...
342      343                             Respighi:Pines of Rome       226
343      344  Schubert: The Late String Quartets & String Qu...       272
344      345                                Monteverdi: L'Orfeo       273
345      346                              Mozart: Chamber Music       274
346      347  Koyaanisqatsi (Soundtrack from the Motion Pict...       275

[347 rows x 3 columns]