In [ ]:
import pandas as pd 

sales_data=pd.read_csv(r"C:\Users\Asus\Downloads\sales_data.csv")

customer_orders=pd.read_csv(r"C:\Users\Asus\Downloads\customer_orders.csv")

In [ ]:
#Homework-1
sales_data.groupby('Category').agg({'Quantity':['sum','mean'],'Price':'mean'})

sales_data.groupby('Category').agg({'Quantity':'sum'}).sort_values(ascending=False,by='Quantity').head(1)

sales_data['totalsales']=sales_data['Quantity']*sales_data['Price']
sales_data.sort_values(by='totalsales',ascending=False).max().Date

            Quantity                  Price
                 sum       mean        mean
Category
Clothing         157   9.235294   31.176471
Electronics      183  10.764706  276.764706
Home             144   9.000000   55.000000

In [ ]:
#Homework-2
cust=customer_orders.groupby('CustomerID').agg({'OrderID':'count'})
cust[cust['OrderID']>20]

data=customer_orders.groupby(['CustomerID',]).agg({'Price':'mean'})
data[data['Price']>120]

total=customer_orders.groupby('Product').agg({'Price':'sum','Quantity':'sum'})
total[total['Quantity']<5]

            OrderID
CustomerID
101              21
102              21

In [ ]:
#homework-3
import sqlite3
import pandas as pd


conn = sqlite3.connect(f"C:\\Users\\Asus\\Downloads\\population.db")
population_df = pd.read_sql_query("SELECT * FROM population", conn)
conn.close()
population_df.groupby('state').agg({"salary":['mean','max','min'],'id':'count'})

In [33]:
population_df

,id,first_name,last_name,email,gender,salary,state
0,1,Armin,Coltart,acoltart0@abc.net.au,Male,368693,District of Columbia
1,2,Mia,Tuddenham,mtuddenham1@addthis.com,Female,154398,Florida
2,3,Kirsteni,Brafield,kbrafield2@arizona.edu,Female,1230304,Georgia
3,4,Phylis,Furlong,pfurlong3@merriam-webster.com,Female,1567795,California
4,5,Wandis,Loveredge,wloveredge4@hatena.ne.jp,Female,1136950,Alabama
...,...,...,...,...,...,...,...
11646,11647,Nell,Perez,nperezhy@flavors.me,Female,1909496,Texas
11647,11648,Ugo,Pethrick,upethrickhz@discuz.net,Male,830390,New Mexico
11648,11649,Hartwell,Hadigate,hhadigatei0@cam.ac.uk,Male,24363,Washington
11649,11650,Avrit,Bastin,abastini1@symantec.com,Female,1869988,Rhode Island
11650,11651,Papageno,Buchanan,pbuchanani2@pagesperso-orange.fr,Male,1271538,Florida