In [ ]:
import pandas as pd 

sales_data=pd.read_csv(r"C:\Users\Asus\Downloads\sales_data.csv")

customer_orders=pd.read_csv(r"C:\Users\Asus\Downloads\customer_orders.csv")

In [ ]:
#Homework-1
sales_data.groupby('Category').agg({'Quantity':['sum','mean'],'Price':'mean'})

sales_data.groupby('Category').agg({'Quantity':'sum'}).sort_values(ascending=False,by='Quantity').head(1)

sales_data['totalsales']=sales_data['Quantity']*sales_data['Price']
sales_data.sort_values(by='totalsales',ascending=False).max().Date

            Quantity                  Price
                 sum       mean        mean
Category
Clothing         157   9.235294   31.176471
Electronics      183  10.764706  276.764706
Home             144   9.000000   55.000000

In [ ]:
#Homework-2
cust=customer_orders.groupby('CustomerID').agg({'OrderID':'count'})
cust[cust['OrderID']>20]

data=customer_orders.groupby(['CustomerID',]).agg({'Price':'mean'})
data[data['Price']>120]

total=customer_orders.groupby('Product').agg({'Price':'sum','Quantity':'sum'})
total[total['Quantity']<5]

            OrderID
CustomerID
101              21
102              21

In [2]:
#homework-3
import sqlite3
import pandas as pd


conn = sqlite3.connect(f"C:\\Users\\Asus\\Downloads\\population.db")
population_df = pd.read_sql_query("SELECT * FROM population", conn)
conn.close()
population_df.groupby('state').agg({"salary":['mean','max','min'],'id':'count'})

                            salary                    id
                              mean      max    min count
state
Alabama               9.750741e+05  1998323  18515   246
Alaska                1.004373e+06  1984665   3678    54
Arizona               1.044695e+06  1988034   7303   253
Arkansas              1.130035e+06  1992899  19945    60
California            9.989894e+05  1998944   1899  1332
Colorado              1.030555e+06  1999129   1192   287
Connecticut           1.004350e+06  1993114   1263   182
Delaware              9.220878e+05  1897296  67517    35
District of Columbia  1.002837e+06  1997136   2344   370
Florida               9.944462e+05  1998236   2184   924
Georgia               9.877976e+05  1999095   9288   326
Hawaii                9.649029e+05  1942831  15397    62
Idaho                 9.695199e+05  1997765   2074    60
Illinois              1.014079e+06  1998860  16655   296
Indiana               9.980216e+05  1997704   5170   226
Iowa                  1.014737e+06  1991852   3184   138
Kansas                9.779326e+05  1984617   9137   145
Kentucky              1.015069e+06  1998173   3045   161
Louisiana             9.886979e+05  1997675   1975   194
Maine                 9.672603e+05  1956418  26856    10
Maryland              9.672597e+05  1980973  31298   143
Massachusetts         9.535666e+05  1988599    553   165
Michigan              9.851175e+05  1997998   3147   209
Minnesota             9.605947e+05  1996528   9962   240
Mississippi           8.929998e+05  1975503  32254    61
Missouri              9.987484e+05  1965817   2245   247
Montana               8.509201e+05  1844963   5066    27
Nebraska              9.682655e+05  1982375   1690    91
Nevada                1.011883e+06  1994171  21874   172
New Hampshire         7.912225e+05  1814893  42695    17
New Jersey            1.002690e+06  1994424   4633   112
New Mexico            9.275264e+05  1918470   3047    72
New York              9.875282e+05  1998712   1404   674
North Carolina        1.035942e+06  1994781   3151   264
North Dakota          9.426285e+05  1943911  96217    27
Ohio                  9.932119e+05  1997533  19860   443
Oklahoma              9.801891e+05  1978204    377   178
Oregon                9.238841e+05  1997814  12673    96
Pennsylvania          1.004587e+06  2000000   2722   350
Rhode Island          1.138828e+06  1973923   7204    17
South Carolina        1.035068e+06  1993952   8337   141
South Dakota          1.179646e+06  1955464  51278    31
Tennessee             9.240579e+05  1971555    230   258
Texas                 9.948307e+05  1999968    241  1293
Utah                  1.042625e+06  1976453    656   120
Vermont               7.798459e+05  1872090  56696     9
Virginia              9.950918e+05  1996748   2304   374
Washington            9.434086e+05  1993675  11736   216
West Virginia         1.057742e+06  1985185  44890   104
Wisconsin             8.602877e+05  1993943   2267   134
Wyoming               9.683462e+05  1367561  27728     5

In [ ]:
def category(salary):
    if salary<100000:
        return 'Low'
    elif salary<500000:
        return 'Mid'
    else:
        return 'HIgh'
population_df['category_salary']=population_df['salary'].apply(category)
population_df.groupby('category_salary').agg({'salary':['min','max','mean'],'id':'count'})